version: '3.3'
services:
  jupyter:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./work:/home/jovyan/work
      - ./data:/data
    ports:
      - 10000:8888
    environment:
      JUPYTER_ENABLE_LAB: 'yes'

